### PR TITLE
#72 Add favorites to Phragmen, Nominators and Accounts (not on colmena repo)

### PR DESCRIPTION
**Pull request by aitorjs**
- Added star on Phragmen page
- Clicking on the star, Phragmen goes to favorites variable or not

### CODE REVIEW

**Comment by aitorjs** [comment]
The changes in the accounts page affect the performance of that page, since it is the only case where the table has many elements, more than 6000 right now.

**Comment by mariopino** [comment]
> The changes in the accounts page affect the performance of that page, since it is the only case where the table has many elements, more than 6000 right now.

Yep! but we don't have to be concerned about performance right now, it should be fixed when the new backend will be finished.

**Comment by mariopino** [comment]
Nice @aitoribanez! Could you please move this PR to https://github.com/Colm3na/polkastats-v2/ repo? creating the branch here, just like the others.

**Comment by aitorjs** [comment]
#84

**Pull request closed without merging**
